#Include <std\metafunc\assert>
#Include <std\metafunc\cmp>
#Include <std\metafunc\hash>
#Include <std\metafunc\iter>
#Include <std\metafunc\len>
#Include <std\metafunc\oneloop>
#Include <std\metafunc\rely>
#Include <std\metafunc\sum>
#Include <std\metafunc\zip>
